name: Build LKMD
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'windows-latest'
            args: ''
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: "wasm32-unknown-unknown"

      - name: Install Trunk
        uses: jetli/trunk-action@v0.5.0
        with:
          version: 'latest'

      - name: Build
        uses: tauri-apps/tauri-action@v0
        id: tauri-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ${{ matrix.args }}
      
      - name: "Upload Artifacts: Application Executable"
        uses: actions/upload-artifact@v4
        with:
          name: "Layered Key Map Display.exe"
          path: ./target/release/*.exe

      - name: "Upload Artifacts: MSI Installer"
        uses: actions/upload-artifact@v4
        with:
          name: "Layered Key Map Display.msi"
          path: ./target/release/bundle/msi/*.msi

      - name: "Upload Artifacts: NSIS Installer"
        uses: actions/upload-artifact@v4
        with:
          name: "Layered Key Map Display.nsis"
          path: ./target/release/bundle/nsis/*.exe
            
